services:
  web:
    image: ghcr.io/alvinmatias69/winv:0.1.1
    container_name: web
    ports:
      - ${PORT}:${PORT}
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./.docker/sql:/docker-entrypoint-initdb.d/
      - ./.docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
