version: '3.9'

services:
  # web:
  #   build:
  #     context: .
  #   container_name: web
  #   ports:
  #     - ${PORT}:${PORT}
  #   environment:
  #     PORT: ${PORT}
  #     DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  #   depends_on:
  #     db:
  #       condition: service_healthy
  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./.docker/sql:/docker-entrypoint-initdb.d/
      - ./.docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
